Removed lodash
maxkorolev/vue-rxjs pull request #3
Opened 2017-08-23 19:41 UTC by Piterden

2017-08-24 06:09 UTC, maxkorolev requested changes

2017-08-24 06:09 UTC, maxkorolev commented on src/pipes.js
> +                    Object.keys().forEach(
Object.keys() should be an Object.keys(vm.$inits)

2017-08-25 01:32 UTC, Piterden commented
Done

2017-08-25 05:21 UTC, merged

2017-08-25 05:37 UTC, Piterden commented
:+1: